updated to use KRaft mode for broker

diff --git a/introduction-to-ksqldb/docker-compose.yml b/introduction-to-ksqldb/docker-compose.yml
--- a/introduction-to-ksqldb/docker-compose.yml
+++ b/introduction-to-ksqldb/docker-compose.yml
@@ -1,36 +1,34 @@
 ---
 version: '3'
 services:
-  zookeeper:
-    image: confluentinc/cp-zookeeper:7.3.2
-    container_name: zookeeper
-    environment:
-      ZOOKEEPER_CLIENT_PORT: 2181
-      ZOOKEEPER_TICK_TIME: 2000
-    # volumes: 
-    #   - ./data/container_data/zk-data:/var/lib/zookeeper/data
-    #   - ./data/container_data/zk-txn-logs:/var/lib/zookeeper/log
 
   broker:
     image: confluentinc/cp-kafka:7.3.2
+    hostname: broker
     container_name: broker
-    depends_on:
-      - zookeeper
     ports:
-      - 9092:9092
+      - "9092:9092"
+      - "9101:9101"
     environment:
       KAFKA_BROKER_ID: 1
-      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
-      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
-      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
-      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,HOST://localhost:9092
-      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
+      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
+      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
+      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
-      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
-    # volumes: 
-    #   - ./data/container_data/kafka-data:/var/lib/kafka/data
+      KAFKA_JMX_PORT: 9101
+      KAFKA_JMX_HOSTNAME: localhost
+      KAFKA_PROCESS_ROLES: 'broker,controller'
+      KAFKA_NODE_ID: 1
+      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
+      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
+      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
+      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
+      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
+    volumes:
+      - ./update_run.sh:/tmp/update_run.sh
+    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
 
   schema-registry:
     image: confluentinc/cp-schema-registry:7.3.2
@@ -50,6 +48,7 @@ services:
     #   docker exec -it ksqldb bash -c 'ksql http://localhost:8088'
     # *-----------------------------*  
     image: confluentinc/ksqldb-server:0.28.2
+    platform: linux/amd64
     container_name: ksqldb
     depends_on:
       - broker
@@ -146,6 +145,16 @@ services:
         #
         sleep infinity
 
+  # ksqldb-cli:
+  #   image: confluentinc/ksqldb-cli:0.28.2
+  #   platform: linux/amd64
+  #   container_name: ksqldb-cli
+  #   depends_on:
+  #     - broker
+  #     - ksqldb
+  #   entrypoint: /bin/sh
+  #   tty: true
+
   # control-center:
   #   image: confluentinc/cp-enterprise-control-center:7.3.2
   #   container_name: control-center
@@ -187,79 +196,80 @@ services:
     # To connect to the DB: 
     #   docker exec -it postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB'
     # *-----------------------------*
-    image: debezium/postgres:12
+    image: debezium/postgres:13
+    platform: linux/amd64
     container_name: postgres
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
 
-  elasticsearch:
-    image: elastic/elasticsearch:7.17.9
-    container_name: elasticsearch
-    ports:
-      - 9200:9200
-    environment:
-      xpack.security.enabled: "false"
-      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
-      discovery.type: "single-node"
-    command:
-      - bash
-      - -c
-      - |
-        /usr/local/bin/docker-entrypoint.sh &
-        echo "Waiting for Elasticsearch to start ⏳"
-        while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) -ne 200 ] ; do
-          echo -e $$(date) " Elasticsearch listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) " (waiting for 200)"
-          sleep 5
-        done
-        echo -e "\n--\n+> Creating Elasticsearch dynamic mapping"
-        curl -XPUT "http://localhost:9200/_template/rmoff_01/" \
-            -H 'Content-Type: application/json' \
-              -d'{ "template": "*", "settings": { "number_of_shards": 1, "number_of_replicas": 0 }, "mappings": { "dynamic_templates": [ { "dates01": { "match": "*TIMESTAMP", "mapping": { "type": "date", "ignore_malformed": true } } }, { "non_analysed_string_template": { "match": "*", "match_mapping_type": "string", "mapping": { "type": "keyword" } } } ] } }'
-        sleep infinity
+  # elasticsearch:
+  #   image: elastic/elasticsearch:7.17.9
+  #   container_name: elasticsearch
+  #   ports:
+  #     - 9200:9200
+  #   environment:
+  #     xpack.security.enabled: "false"
+  #     ES_JAVA_OPTS: "-Xms1g -Xmx1g"
+  #     discovery.type: "single-node"
+  #   command:
+  #     - bash
+  #     - -c
+  #     - |
+  #       /usr/local/bin/docker-entrypoint.sh &
+  #       echo "Waiting for Elasticsearch to start ⏳"
+  #       while [ $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) -ne 200 ] ; do
+  #         echo -e $$(date) " Elasticsearch listener HTTP state: " $$(curl -s -o /dev/null -w %{http_code} http://localhost:9200/) " (waiting for 200)"
+  #         sleep 5
+  #       done
+  #       echo -e "\n--\n+> Creating Elasticsearch dynamic mapping"
+  #       curl -XPUT "http://localhost:9200/_template/rmoff_01/" \
+  #           -H 'Content-Type: application/json' \
+  #             -d'{ "template": "*", "settings": { "number_of_shards": 1, "number_of_replicas": 0 }, "mappings": { "dynamic_templates": [ { "dates01": { "match": "*TIMESTAMP", "mapping": { "type": "date", "ignore_malformed": true } } }, { "non_analysed_string_template": { "match": "*", "match_mapping_type": "string", "mapping": { "type": "keyword" } } } ] } }'
+  #       sleep infinity
 
-  kibana:
-    image: elastic/kibana:7.17.9
-    container_name: kibana
-    hostname: kibana
-    depends_on:
-      - elasticsearch
-    ports:
-      - 5601:5601
-    environment:
-      xpack.security.enabled: "false"
-      discovery.type: "single-node"
-    command:
-      - bash
-      - -c
-      - |
-        /usr/local/bin/kibana-docker &
-        echo "Waiting for Kibana to be ready ⏳"
-        while [ $$(curl -H 'kbn-xsrf: true' -s -o /dev/null -w %{http_code} http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) -ne 200 ] ; do 
-          echo -e "\t" $$(date) " Kibana saved objects request response: " $$(curl -H 'kbn-xsrf: true' -o /dev/null -w %{http_code} -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) $$(curl -H 'kbn-xsrf: true' -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) " (waiting for 200)"
-          sleep 5  
-        done
+  # kibana:
+  #   image: elastic/kibana:7.17.9
+  #   container_name: kibana
+  #   hostname: kibana
+  #   depends_on:
+  #     - elasticsearch
+  #   ports:
+  #     - 5601:5601
+  #   environment:
+  #     xpack.security.enabled: "false"
+  #     discovery.type: "single-node"
+  #   command:
+  #     - bash
+  #     - -c
+  #     - |
+  #       /usr/local/bin/kibana-docker &
+  #       echo "Waiting for Kibana to be ready ⏳"
+  #       while [ $$(curl -H 'kbn-xsrf: true' -s -o /dev/null -w %{http_code} http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) -ne 200 ] ; do 
+  #         echo -e "\t" $$(date) " Kibana saved objects request response: " $$(curl -H 'kbn-xsrf: true' -o /dev/null -w %{http_code} -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) $$(curl -H 'kbn-xsrf: true' -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) " (waiting for 200)"
+  #         sleep 5  
+  #       done
 
-        echo -e "\t" $$(date) " Kibana saved objects request response: " $$(curl -H 'kbn-xsrf: true' -o /dev/null -w %{http_code} -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) $$(curl -H 'kbn-xsrf: true' -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*)
+  #       echo -e "\t" $$(date) " Kibana saved objects request response: " $$(curl -H 'kbn-xsrf: true' -o /dev/null -w %{http_code} -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*) $$(curl -H 'kbn-xsrf: true' -s http://localhost:5601/api/saved_objects/_find?type=index-pattern&search_fields=title&search=*)
 
-        echo -e "\n--\n+> Pre-creating index pattern"
-        curl -s -XPOST 'http://localhost:5601/api/saved_objects/index-pattern/orders_enriched' \
-          -H 'kbn-xsrf: nevergonnagiveyouup' \
-          -H 'Content-Type: application/json' \
-          -d '{"attributes":{"title":"orders_enriched","timeFieldName":"ORDER_TIMESTAMP"}}'
+  #       echo -e "\n--\n+> Pre-creating index pattern"
+  #       curl -s -XPOST 'http://localhost:5601/api/saved_objects/index-pattern/orders_enriched' \
+  #         -H 'kbn-xsrf: nevergonnagiveyouup' \
+  #         -H 'Content-Type: application/json' \
+  #         -d '{"attributes":{"title":"orders_enriched","timeFieldName":"ORDER_TIMESTAMP"}}'
 
-        echo -e "\n--\n+> Setting the index pattern as default"
-        curl -s -XPOST 'http://localhost:5601/api/kibana/settings' \
-          -H 'kbn-xsrf: nevergonnagiveyouup' \
-          -H 'content-type: application/json' \
-          -d '{"changes":{"defaultIndex":"orders_enriched"}}'
+  #       echo -e "\n--\n+> Setting the index pattern as default"
+  #       curl -s -XPOST 'http://localhost:5601/api/kibana/settings' \
+  #         -H 'kbn-xsrf: nevergonnagiveyouup' \
+  #         -H 'content-type: application/json' \
+  #         -d '{"changes":{"defaultIndex":"orders_enriched"}}'
 
-        echo -e "\n--\n+> Opt out of Kibana telemetry"
-        curl 'http://localhost:5601/api/telemetry/v2/optIn' \
-            -H 'kbn-xsrf: nevergonnagiveyouup' \
-            -H 'content-type: application/json' \
-            -H 'accept: application/json' \
-            --data-binary '{"enabled":false}' \
-            --compressed
+  #       echo -e "\n--\n+> Opt out of Kibana telemetry"
+  #       curl 'http://localhost:5601/api/telemetry/v2/optIn' \
+  #           -H 'kbn-xsrf: nevergonnagiveyouup' \
+  #           -H 'content-type: application/json' \
+  #           -H 'accept: application/json' \
+  #           --data-binary '{"enabled":false}' \
+  #           --compressed
 
-        sleep infinity
+  #       sleep infinity
